# Generated by Django 2.2.4 on 2019-08-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('frequency', models.BigIntegerField()),
            ],
        ),
    ]
